export const SET_USER_LOCATION = "SET_USER_LOCATION"
export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST"
export const NEARBY_SHOPS = "NEARBY_SHOPS"
export const NEARBY_SHOPS_FETCHED = 'NEARBY_SHOPS_FETCHED'