export const SET_USER_LOCATION = "SET_USER_LOCATION"
export const NEARBY_SHOPS = "NEARBY_SHOPS"
export const NEARBY_SHOPS_FETCHED = 'NEARBY_SHOPS_FETCHED'
export const SENDING_REQUEST = "SENDING_REQUEST"
export const REQUEST_ERROR = "REQUEST_ERROR"
export const CLEAR_ERROR = "CLEAR_ERROR"
export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST"